name: update each level and readme in main
on:
  fork:
  workflow_dispatch:
    
jobs:
  level-2:
    name: advance upstream level-2
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: level-2
      - name: set up python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: update readme
        run: |
          python .update_readme.py "`date`"
      - name: commit and push
        run: |-
          git config --global user.email "318383724@qq.com"
          git config --global user.name "orangex4-bot"
          git add -A
          git commit -m ":robot:: Add a new commit" || exit 0
          git push origin level-2

  level-3: 
    name: advance upstream level-3
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: level-3
      - name: set up python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name:  update readme
        run: |
          python .update_readme.py
      - name: commit and push
        run: |-
          git config --global user.email "318483724@qq.com"
          git config --global user.name "orangex4-bot"
          git add -A
          git commit -m ":robot:: Add a new commit" || exit 0
          git push origin level-3

